### ISSUE TITLE
viniette and/or calc_pi

### ISSUE THREAD

**Issue by samasafish** [hemstrow/snpR#13]
**Hi Will,

This is Sam, I was in the zoom meeting when you demo'd the snpR package to Gordon Luikart at our PopGen seminar (UMT). Thanks for the introduction! I tried to load the vignette and it threw an error:**

> remotes::install_github("hemstrow/snpR",build_vignettes = T, force = T)
Downloading GitHub repo hemstrow/snpR@master
✓  checking for file ‘/private/var/folders/sw/mrnl2xx50rv0s050dy76b53m0000gn/T/RtmpmIDXzm/remotes1829b1566f68c/hemstrow-snpR-ad226be/DESCRIPTION’ ...
─  preparing ‘snpR’:
✓  checking DESCRIPTION meta-information ...
─  installing the package to build vignettes
E  creating vignettes (36.3s)
   --- re-building ‘snpR_introduction.Rmd’ using rmarkdown
   Quitting from lines 184-191 (snpR_introduction.Rmd) 
   Error: processing vignette 'snpR_introduction.Rmd' failed with diagnostics:
   (list) object cannot be coerced to type 'double'
   --- failed re-building ‘snpR_introduction.Rmd’
   
   SUMMARY: processing the following file failed:
     ‘snpR_introduction.Rmd’
   
   Error: Vignette re-building failed.
   Execution halted

**So I opened your rmarkdown and tried to knit it myself and found that the calc_pi() function was throwing this error:**

Quitting from lines 176-182 (snpr_viniette.Rmd) 
Error in fun(ac, ...) : (list) object cannot be coerced to type 'double'
Calls: <Anonymous> ... eval -> calc_pi -> apply.snpR.facets -> <Anonymous> -> fun
Execution halted

**After commenting out line 178 it knitted past that chunk but also failed at the calc_basic_snp_stats() on line 358 onward since that calls calc_pi(). I set these chunks to be ignored and it knitted perfectly. Just FYI. Are there dependencies I'm missing for this function?

Thanks!

Sam**

**Comment by hemstrow** [comment]
Hey Sam,

Sorry for responding slowly, didn't see the issue until now.

I made quite a few changes to the vignette and fixed some bugs since you gave this a try. The vignette should knit now if you give it another try. Please let me know if it doesn't and I can take another look!
