### ISSUE TITLE
Importing files

### ISSUE THREAD

**Issue by elizeng** [hemstrow/snpR#40]
Hi @hemstrow I am trying to use snpR to run NeEstimator but am having problems with the input file.

I first tried a vcf file input via vcfR, but I am met with an error which I am not sure how to solve
```
> vcf <- read.vcfR("file.vcf", verbose = FALSE) #convert from vcfR to snpR format
> vcf2<-import.snpR.data(vcf) #convert from vcfR to snpR format
Warning message:
In validityMethod(object) :
  Some snp metadata columns contain unacceptable special characters. Unaccepted characters: '.', '~', or any whitespace.
These can cause unexpected behaviour if the subect columns are used as facets.

> is.snpRdata(vcf2) #Check if vcf file is in snpR format
[1] TRUE
> calc_ne(vcf2, methods = "LD",
+         NeEstimator_path = "Ne2-1.exe",
+         verbose=TRUE)
Error in if (input == "" || length(grep("\\n|\\r", input))) { : 
  missing value where TRUE/FALSE needed
```

I then tried another mode of inputting data, using a structure file, but it seems to be looking for a snp metadata file, to which I input a map file, but to no avail. 
```
> import.snpR.data("strfile",
+                  rows_per_individual=2, header_cols=1 , marker_and_sample_names=TRUE, verbose=TRUE)
Assuming single nucleotide format.
Error in import.snpR.data(x, sample.meta = sample.meta, snp.meta = headers,  : 
  Cannot locate snp.meta file.
In addition: Warning message:
In if (file.exists(snp.meta)) { :
  the condition has length > 1 and only the first element will be used
```

.txt extension has been added to the input file uploaded because github does not accept it otherwise

[file.vcf.txt](https://github.com/hemstrow/snpR/files/9857775/file.vcf.txt)
[strfile.txt](https://github.com/hemstrow/snpR/files/9857809/strfile.txt)

**Comment by hemstrow** [comment]
Hey @elizeng!

Ok, it looks like the
```{r}
Error in if (input == "" || length(grep("\\n|\\r", input))) { : 
  missing value where TRUE/FALSE needed
```
error occurs when the NeEstimator path does go to a valid file, but not one that actually runs something. I'd double check that that path actually goes to the executable correctly! I've pushed a hotfix to do a more thorough test for the NeEstimator exe and return a more informative error message.

As a side note, it looks like your vcf reads in perfectly with both the `read_vcf` and `import.snpR.data` functions. The warning is just there to let you know to avoid using an metadata columns with those characters as facets, since those are reserved characters for facet processing internally.

The str file should read in OK if you:
* Change the deliminator to something consistent (like tabs OR spaces but not both, since `data.table::fread()` can't handle that).
* Remove the "Name" header. I also adjusted the argument names and documentation to note that the header row should contain only marker names, not sample metadata. You'll also need to set the `header_cols` argument to 2, since you have both sample names and pop info in the str file!
* change the extension to ".str"
It should read in OK with `read_structure()` in that case!

Thanks for your feedback, and let me know if you have any other issues!

**Comment by elizeng** [comment]
Thanks for the prompt response @hemstrow 

I think the path to NeEstimator did not enjoy the space in part of the directory although it worked fine for the input file. It should be working now, but will get back if there are any further errors.

For the structure file, thanks for the insight on the consistency. It was a default output and after changing it now works. Although it did come up with this warning, but should be fine. 
```
Warning message:
In .sub_and_t_1_2_to_A_C(dat, num_individuals) :
  Since allelic identities are not clear, alleles at each locus will be saved as A and C. If this data is later reformatted for use elsewhere, please be aware that this may cause issues for some downstream analyses (since, for example, all SNPs will be nonsensically noted as transversions rather than transitions!).
 To prevent this, use a different format that specifies allelic identities.
This is not an issue for any snpR functions save those that rely on ancestral/derived allelic identities.
```

It would be useful to have `read_structure` along with other wrapper functions documented somewhere. I was not able to access the viginette and was referring to the documentation here: https://rdrr.io/github/hemstrow/snpR/man/

Thanks again!!

**Comment by hemstrow** [comment]
Also, the readme (github splash page for snpR) now has a function table of contents, which should be helpful.

**Comment by elizeng** [comment]
> Glad it's figured out! Did the vignette fail to build for you?

I installed the package by using `remotes::install_github("hemstrow/snpR")` which worked fine, but does not build the viginette.

When I try with the recommended line to build viginettes, it somehow fails.

> remotes::install_github("hemstrow/snpR", build_vignettes = T, build_opts = c("--no-resave-data", "--no-manual"))
Downloading GitHub repo hemstrow/snpR@HEAD
These packages have more recent versions available.
It is recommended to update all of them.
Which would you like to update?

 1: All                                  
 2: CRAN packages only                   
 3: None                                 
 4: stringi     (1.6.1  -> 1.7.8 ) [CRAN]
 5: magrittr    (2.0.1  -> 2.0.3 ) [CRAN]
 6: glue        (1.4.2  -> 1.6.2 ) [CRAN]
 7: Rcpp        (1.0.6  -> 1.0.9 ) [CRAN]
 8: colorspace  (2.0-1  -> 2.0-3 ) [CRAN]
 9: cli         (2.5.0  -> 3.4.1 ) [CRAN]
10: viridisLite (0.4.0  -> 0.4.1 ) [CRAN]
11: rlang       (0.4.11 -> 1.0.6 ) [CRAN]
12: lifecycle   (1.0.1  -> 1.0.3 ) [CRAN]
13: farver      (2.1.0  -> 2.1.1 ) [CRAN]
14: vctrs       (0.3.8  -> 0.5.0 ) [CRAN]
15: utf8        (1.2.1  -> 1.2.2 ) [CRAN]
16: fansi       (0.4.2  -> 1.0.3 ) [CRAN]
17: pillar      (1.7.0  -> 1.8.1 ) [CRAN]
18: stringr     (1.4.0  -> 1.4.1 ) [CRAN]
19: plyr        (1.8.6  -> 1.8.7 ) [CRAN]
20: tibble      (3.1.1  -> 3.1.8 ) [CRAN]
21: scales      (1.1.1  -> 1.2.1 ) [CRAN]
22: isoband     (0.2.4  -> 0.2.6 ) [CRAN]
23: gtable      (0.3.0  -> 0.3.1 ) [CRAN]
24: digest      (0.6.27 -> 0.6.30) [CRAN]
25: tidyselect  (1.1.1  -> 1.2.0 ) [CRAN]
26: generics    (0.1.2  -> 0.1.3 ) [CRAN]
27: rbibutils   (2.1.1  -> 2.2.9 ) [CRAN]
28: purrr       (0.3.4  -> 0.3.5 ) [CRAN]
29: ggplot2     (3.3.5  -> 3.3.6 ) [CRAN]
30: matrixStats (0.58.0 -> 0.62.0) [CRAN]
31: dplyr       (1.0.6  -> 1.0.10) [CRAN]
32: data.table  (1.14.0 -> 1.14.4) [CRAN]

Enter one or more numbers, or an empty line to skip updates: 3
WARNING: Rtools is required to build R packages, but is not currently installed.

Please download and install Rtools 3.5 from https://cran.r-project.org/bin/windows/Rtools/.
√  checking for file 'C:\Users\yxeng\AppData\Local\Temp\RtmpI9YXGs\remotes92e82e2c6c7\hemstrow-snpR-8ca0045/DESCRIPTION' ...
-  preparing 'snpR': (1.2s)
√  checking DESCRIPTION meta-information ... 
   Error in loadVignetteBuilder(pkgdir, TRUE) : 
     vignette builder 'knitr' not found
   Execution halted
Error: Failed to install 'snpR' from GitHub:
  System command 'Rcmd.exe' failed, exit status: 1, stdout & stderr were printed

**Comment by elizeng** [comment]
> Also, the readme (github splash page for snpR) now has a function table of contents, which should be helpful.

Thanks for adding it, its very useful and informative on the commands available!
