### ISSUE TITLE
Output file from calc_ne

### ISSUE THREAD

**Issue by elizeng** [hemstrow/snpR#42]
Hi again @hemstrow,

Now that the input files work, I tested the run with a small dataset of 1000 loci on both windows and linux.
On the windows it works fine, and the output defaults to the R working directory.

On the linux (HPC Cluster) the program runs fine but the output file is no where to be found, even when the working directory is set.

```
> setwd("/scratch/yxeng/other_projects/test")
> calc_ne(vcf2, methods = "LD",NeEstimator_path="/u/yxeng/programs/NeEstimator_64_bit_191125/NeEstimator_64_bit_191125/Ne2-1L",
+ outfile="Ne_out",
+         verbose=TRUE)
arguments 'show.output.on.console', 'minimized' and 'invisible' are for Windows only
Number of loci = 1000, 2-digit alleles
Input file: snps.gen - GENEPOP format
Number of loci = 1000, 2-digit alleles
Method(s): LD
Locus names - last 6 characters: (only the last 100 are listed)
NP_901 NP_902 NP_903 NP_904 NP_905 NP_906 NP_907 NP_908 NP_909 NP_910
NP_911 NP_912 NP_913 NP_914 NP_915 NP_916 NP_917 NP_918 NP_919 NP_920
NP_921 NP_922 NP_923 NP_924 NP_925 NP_926 NP_927 NP_928 NP_929 NP_930
NP_931 NP_932 NP_933 NP_934 NP_935 NP_936 NP_937 NP_938 NP_939 NP_940
NP_941 NP_942 NP_943 NP_944 NP_945 NP_946 NP_947 NP_948 NP_949 NP_950
NP_951 NP_952 NP_953 NP_954 NP_955 NP_956 NP_957 NP_958 NP_959 NP_960
NP_961 NP_962 NP_963 NP_964 NP_965 NP_966 NP_967 NP_968 NP_969 NP_970
NP_971 NP_972 NP_973 NP_974 NP_975 NP_976 NP_977 NP_978 NP_979 NP_980
NP_981 NP_982 NP_983 NP_984 NP_985 NP_986 NP_987 NP_988 NP_989 NP_990
NP_991 NP_992 NP_993 NP_994 NP_995 NP_996 NP_997 NP_998 NP_999 P_1000
Outputs are written to file Ne_out.txt
Tabular-format LD Output File Name: Ne_outxLD.txt
Starting time: Wed Oct 26 11:03:17 2022

Population     1 [WSP_C_01_1]
-> Total samples = 11
   * For lowest freq: 0.050
       Estimate of Ne:                -19.7
     Parameter CI:        infinite        infinite
     Jackknife CI:        infinite        infinite
   * For lowest freq: 0.020
       Estimate of Ne:                -23.5
     Parameter CI:        infinite        infinite
     Jackknife CI:        infinite        infinite
   * For lowest freq: 0.010
       Estimate of Ne:                -23.5
     Parameter CI:        infinite        infinite
     Jackknife CI:        infinite        infinite
   * For lowest freq:    0+
       Estimate of Ne:                -23.5
     Parameter CI:        infinite        infinite
     Jackknife CI:        infinite        infinite
snpRdata with 1000 SNPs and 11 samples.
 ==============================================
 Average minor allele frequency: 0.2311364
 Minimum minor allele frequency: 0.04545455
 Percent missing data: 0
 ==============================================
 Possible sample metadata facets:
 sampID .sample.id

 Possible SNP metadata facets:
 CHROM  position        ID      REF     ALT     QUAL    FILTER  .snp.id

 ==============================================
 Currently tabulated facets:
 .base

 Currently calculated statistics:
 Facet:  .base
 maf, ne

 Calculated statistics can be accessed via get.snpR.stats()
 ==============================================
```

The only time a hint of an output is seen is when the outfile directory is included in the `outfile=` flag, but that fails because its supposedly for just the prefix of the output file. This will create a NeEstimator folder within the working directory, but there will be no output because it did not run. On windows, including the directory for the outfile fails with the same error.

```
> calc_ne(vcf2, methods = "LD",NeEstimator_path="/u/yxeng/programs/NeEstimator_64_bit_191125/NeEstimator_64_bit_191125/Ne2-1L",
+ outfile="/scratch/yxeng/other_projects/test/Ne_out",
+         verbose=TRUE)
arguments 'show.output.on.console', 'minimized' and 'invisible' are for Windows only
Number of loci = 1000, 2-digit alleles
Error in if (input == "" || length(grep("\\n|\\r", input))) { :
  missing value where TRUE/FALSE needed
```

Another thing I note is that, when you run replicates, the program creates a new folder within the current NeEstimator folder. So the later runs end up being buried deep within the prior NeEstimator folders. Not sure if this is an intended output.

**Comment by hemstrow** [comment]
I think the issue is that your `outfile` is a directory instead of just a prefix, which the function isn't expecting. If you need to send it to scratch, I'd recommend putting `cd /scratch/yxeng/other_projects/test/` in a shell script before running whatever R script you are using to do ne estimation! This is unclear in the current documentation--I just pushed a clarification and added a sanity check to catch this to `calc_ne()`. As a side note--thanks for reaching out with issues! It has really helped me clarify and make usage more clearer.

Note that if the function errors out midway through it'll leave your working directory set to the NeEstimator folder it creates to store input and output files, since it moves your working directory back after finishing (I know how to fix this, but it's a bit of a pain and I haven't gotten around to it yet). If it runs without errors you shouldn't have that problem!

Note that you need to set the `cleanup = FALSE` to avoid removing output files--otherwise ne values are just available in the `snpRdata` object after you run `calc_ne()`. Here's an example that runs on my linux install:

```{r}
# read and subsample
vcf <- "/mnt/c/Users/Will/Downloads/file.vcf"
vcf <- read_vcf(vcf)
vcf <- vcf[sample(nrow(vcf), 1000),]

# calc and fetch
ne <- calc_ne(vcf, NeEstimator_path = "~/bin/Ne2-1L", verbose = TRUE, cleanup = FALSE, outfile = "test")
get.snpR.stats(vcf, stats = "ne")$pop
```

**Comment by elizeng** [comment]
Changing the directory to where I want the output file worked like a charm, the output now exist!
Will now try running it on my dataset and write back to let you know how it goes.

Thanks for the prompt advice and amazing work here :)
