### ISSUE TITLE
can not find Ne2-1.exe

### ISSUE THREAD

**Issue by ezcn** [hemstrow/snpR#44]
Hi, 

I am trying to use calc_ne and i get this error message: 

Error in calc_ne(dat, NeEstimator_path = "/usr/bin/Ne2-1.exe") : 
  NeEstimator executable not found at provided path.

I searched for Ne2-1.exe in your repo to be able to specify a path but I could not find it
Can you help on that ? 
thanks!

**Comment by hemstrow** [comment]
Hey @ezcn!

This argument is looking for a path to the executable for NeEstimator on your computer. [NeEstimator is an external program](http://www.molecularfisherieslaboratory.com.au/neestimator-software/) that is called by snpR to calculate Ne. You'll need to download this, then provide the path to the executable to the NeEstimator_path argument.

Note that [this issue](https://github.com/hemstrow/snpR/issues/42) also has some calc_ne recommendations, and that the path to your NeEstimator file probably needs to be a standard one (e.g. no spaces, etc--I believe a recent change should mostly work around this but I'm not positive that it'll work in _all_ cases).

**Comment by hemstrow** [comment]
Hey there, I'm going to go ahead and close this issue--please let me know if you are still having problems, I am happy to help!
