### ISSUE TITLE
Issues with snpR 1.2.9.2.

### ISSUE THREAD

**Issue by WickEmm** [hemstrow/snpR#65]
Dear William,

I am using snpR 1.2.9.2 with R version 4.4.0.
I experienced several crashes these days ,
1. using calc_smoothed_averages :R and Rstudio run, then freeze and dont't ever respond.

My code:

tr4.dat10<-calc_smoothed_averages(tr4.dat10,
                                facets=c("Country","SC_DAPC","SC_DAPC.CHROM","Country.CHROM","Geo_Region.CHROM","SC_DAPC.Year_range"),
                                sigma=50,
                                step=100,
                                triple_sigma=FALSE,
                                par=4)

2. similar problem using do.bootstrap
My code:
tr4.dat10<-do_bootstraps(tr4.dat10,
                         facets=c("SC_DAPC.CHROM","Country.CHROM","Geo_Region.CHROM","SC_DAPC.Year_range"),
                         boots=1000,
                         sigma=50,
                         step=100,
                         par=4,
                         triple_sigma=FALSE)

Thanks for your help,

**Comment by hemstrow** [comment]
Hey @WickEmm,

Hmm, that's interesting. Freezes are harder to diagnose given the lack of error messages--would you feel comfortable sharing your dataset? If so, you can email it to me at hemstrow@gmail.com. Those two functions are fairly memory intensive, which might be the issue, although with so few bootstraps `do_bootstraps` should run without much need for resources.

**Comment by hemstrow** [comment]
I believe we've got the problem with `do.bootstraps` fixed in the dev version, although the underlying problem (`calc_smoothed_averages` occasionally produces duplicated output rows) still exists.
